// This file contains code to connect to the DB

// Need to include this once from main app
var mongoose = require('mongoose');

// Use native promises (or else mongoose will warn about a deprecated implementation)
mongoose.Promise = global.Promise;  

//var dbDomain = "localhost";
//var dbName = "proj";
//var dbUri = "mongodb://" + dbDomain + "/" + dbName;
var dbUri = 'mongodb://dbuser:dbpassword@ds050879.mlab.com:50879/csci2720finalprojdb';

mongoose.connect(dbUri);

var db = mongoose.connection;

db.on('error', function(err) {
  console.log("Connection error: " + err);
});

db.once('open', function() {
  //console.log("Connected to " + dbName);
});


// Note: On some terminal, SIGINT might not be generated by pressing CTRL-C
process.on('SIGINT', function() {
  mongoose.connection.close(function() {
    console.log('Mongoose disconnected via app termination');
    process.exit(0);
  });
});

